### PR TITLE
use UID 1001 for the persistant volume mount to match initialization UID

### PR DESCRIPTION
**Pull request by StephanX**
This pull request addresses a filesystem permissions error.  Reference: https://github.com/bitnami/bitnami-docker-redis/issues/87

### CODE REVIEW

**Comment by prydonius** [comment]
What type of PV provisioning is setup on your cluster? I haven't seen this issue with Minikube (HostPath) or GKE (GCE-PD).

**Comment by 34code** [comment]
I'm having the same issue .. im using the default storage class

`Default: volume.alpha.kubernetes.io/storage-class: default`

**Comment by prydonius** [comment]
Ah I now understand why this is needed! I didn't realise it was due to the non-root change.

cc'ing @sameersbn because he had a different solution in https://github.com/kubernetes/charts/pull/2380/files#diff-ce347aed3be8e5790b15443e71eb23ddR24.

The initContainer with `chmod -R g+rwX /bitnami` keeps the assumption that we don't know what uid the container will run as (something that is important in contexts like OpenShift since the container is assigned a random UID).

How does fsGroup work? I assumed from the name that this will only set the GID of the mount and not the UID, so shouldn't this still cause filesystem permission issues?

**Comment by sameersbn** [comment]
Nice! I need to check out the ` spec.securityContext.fsGroup` setting. If it resolved the volume permission issue, then it definitely is a clean solution. Probably we should specify the `runAsUser` param as well if it all checks out.

**Pull request merged**
